export const assets = {
  logoIcon: "/assets/logo-icon.png",
  logoMain: "/assets/logo-main.png",
  logoDdakpool: "/assets/logo-ddakpool.png",
  logoAuth: "/assets/logo-auth.png",
  iconSettings: "/assets/icon-settings.svg",
  iconChevronDownWhite: "/assets/icon-chevron-down-white.svg",
  iconFilterAlt: "/assets/icon-filter-alt.svg",
  iconTabGrid: "/assets/icon-tab-grid.svg",
  iconTabFolder: "/assets/icon-tab-folder.svg",
  iconTabFolderOpen: "/assets/icon-tab-folder-open.svg",
  iconFolderFilled: "/assets/icon-folder-filled.svg",
  iconEdit: "/assets/icon-edit.svg",
  iconDelete: "/assets/icon-delete.svg",
  iconAddCircle: "/assets/icon-add-circle.svg",
  iconBookmark: "/assets/icon-bookmark.svg",
  iconCheck: "/assets/icon-check.svg",
  iconMoreHoriz: "/assets/icon-more-horiz.svg",
  iconClose: "/assets/icon-close.svg",
  iconSearch: "/assets/icon-search.svg",
  iconBack: "/assets/icon-back.svg",
  iconDdakpoolMark: "/assets/icon-ddakpool-mark.svg",
  iconDetailBriefcase: "/assets/icon-detail-briefcase.svg",
  iconDetailSparkles: "/assets/icon-detail-sparkles.svg",
  iconDetailBuilding: "/assets/icon-detail-building.svg",
  iconDetailFile: "/assets/icon-detail-file.svg",
  iconDetailSend: "/assets/icon-detail-send.svg",
  iconDetailUser: "/assets/icon-detail-user.svg",
  iconDetailPin: "/assets/icon-detail-pin.svg",
  iconDetailClose: "/assets/icon-detail-close.svg",
  iconDetailChevron: "/assets/icon-detail-chevron.svg",
  iconDetailFileStar: "/assets/icon-detail-file-star.svg",
  iconDetailUpload: "/assets/icon-detail-upload.svg",
  iconDetailWriting: "/assets/icon-detail-writing.svg",
  iconSortCaret: "/assets/icon-sort-caret.png",
  iconModalExclamation: "/assets/icon-modal-exclamation.svg",
  iconModalSuccess: "/assets/icon-modal-success.svg",
  iconModalLoading: "/assets/icon-modal-loading.svg",
  iconToastCheck: "/assets/icon-toast-check.svg",
  iconGrid: "/assets/icon-grid.png",
  iconChevron: "/assets/icon-chevron.png",
  iconChevronDownYellow: "/assets/icon-chevron-down-yellow.png",
  carousel: [
    "/assets/carousel-01.png",
    "/assets/carousel-02.png",
    "/assets/carousel-03.png",
    "/assets/carousel-04.png",
  ],
  onboarding: [
    "/assets/onboarding-01.png",
    "/assets/onboarding-02.png",
    "/assets/onboarding-03.png",
  ],
  listEmpty: "/assets/empty-state.png",
} as const;
